### ISSUE TITLE
Missing usage example

### ISSUE THREAD

**Issue by lfarah** [JKalash/Croc#1]
Hey @JKalash, nice library! Please add an example of how to use Croc

**Comment by lfarah** [comment]
Please fix this before we can approve [your PR on AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/2408)

**Comment by JKalash** [comment]
@lfarah Done 😁
[PR](https://github.com/vsouza/awesome-ios/pull/2408)

**Comment by lfarah** [comment]
Thanks!
